### PR TITLE
CI for Documentation and tests

### PR DESCRIPTION
**Pull request by briederer**
This should add the needed CI for creating docs on push/pull requests to master as discussed in #5.

### CODE REVIEW

**Comment by fzierler** [comment]
Nice! I think it is sufficient if we only test on 1.6 and nightly since 1.5 is no longer maintained and 1.0.5 LTS will soon (at the time of the 1.7 release in about 2-3 months) be replaced by 1.6 as LTS.

**Comment by briederer** [comment]
When the checks have finished I guess everything works and it is ready to be merged (this time with squash/merge 😉)
I also added a workflow to the gh-pages branch which should be executed when merging the PR to master and clean the PR-preview webpages.

**Comment by briederer** [comment]
> Nice! I think it is sufficient if we only test on 1.6 and nightly since 1.5 is no longer maintained and 1.0.5 LTS will soon (at the time of the 1.7 release in about 2-3 months) be replaced by 1.6 as LTS.

I would keep it as it is for now and with the release of 1.7 and the change of the LTS also change the CI.

**Comment by fzierler** [comment]
Looks good to me. I'll merge and look at code coverage in a separate PR.

**Pull request merged**
