### PR TITLE
[WIP] Adding basic infos to Readme

### PR DESCRIPTION
**Pull request by briederer**
I've added general infos and the structure to the readme-file.
I'll keep this PR open until everything is filled with at least the basics for each section.

### CODE REVIEW

**Comment by fzierler** [comment]
Looks good. I'd prefer if you add my uni-graz.at email instead of the other one. :)

**Comment by briederer** [comment]
> I'd prefer if you add my uni-graz.at email instead of the other one. :)
Sure no problem.
Any other Contact details you would like to have in the readme?

**Comment by fzierler** [comment]
>> I'd prefer if you add my uni-graz.at email instead of the other one. :)
>>Sure no problem.

>  Any other Contact details you would like to have in the readme?

Currently there are no other contact details. In case I change my mind on get a twitter account then I will update the readme. :)

**Comment by briederer** [comment]
Should we also set the README file as the main page for the docs?

**Comment by fzierler** [comment]
Please squash and force push on this branch before merging. The other email address already gets enough spam and the spam filter on it is quite lousy so I don't want it to be in this git-history. ;) Thank you!  

Edit. If you want I can also do that before I merge.

**Comment by briederer** [comment]
I don't have time now, and it is not ready to be merged yet. 
But I'll do so then.

**Comment by briederer** [comment]
I guess this is ready now to be merged.
It doesn't make sense to write the usage and Special Features section of the README-file before we have added functionality for that.

**Pull request merged**
